version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_DB=indicar-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-volume:
    driver: local

networks:
  app-network:
    driver: bridge