version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      - MYSQL_DATABASE=indicar-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    expose:
      - '3308'
    networks:
      - app-network

  app:
    build: .
    container_name: go-app
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql-volume:
    driver: local

networks:
  app-network:
    driver: bridge
