name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push Docker image
        uses: docker/build-push-action@v4
        with:
           context: .
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/indicar-api:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/indicar-api:latest
      - name: Create .env on runner
        run: |
          cat > .env <<EOF
          DB_HOST=${{ secrets.DB_HOST }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          EOF

      - name: Run DB migrations (one-off)
        run: |
          docker run --rm \
            --env-file .env \
            --name indicar-api-migrate \
            ${{ secrets.DOCKER_USERNAME }}/indicar-api:latest -migrate

      - name: Restart API container
        run: |
          docker stop indicar-api || true
          docker rm indicar-api || true
          docker run -d \
            --restart unless-stopped \
            --env-file .env \
            -p 80:8080 \
            --name indicar-api \
            ${{ secrets.DOCKER_USERNAME }}/indicar-api:latest
      